### PR TITLE
Add more detail for setup

### PR DESCRIPTION
**Pull request by dacook**
This covers more things that were covered in the wiki. Now the wiki can simply link to this section. (_**update to wiki required on merge**_)
Alternatively, we could move this content to the wiki and link to it there.

Best viewed with whitespace ignored.

### CODE REVIEW

**Comment by dacook** [comment]
Build failure, but it wouldn't be related to changing the readme: https://github.com/openfoodfoundation/ofn-install/actions/runs/3441297507/jobs/5740681774

I think @heroinedor is working on that, but I don't see an issue for it yet.

**Comment by jibees** [comment]
Build failed in ofn-install repo is a long (mid?) term work for @heroinedor yes!

**Review by jibees — APPROVED** [review]
👍

**Comment by dacook** [comment]
Thanks, have updated wiki: https://github.com/openfoodfoundation/ofn-install/wiki/Setup

**Pull request merged**
