### PR TITLE
Bump US and CA to three unicorn workers

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
Related to https://github.com/openfoodfoundation/openfoodnetwork/issues/6802

:unicorn::unicorn::unicorn:

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
They can probably handle 4, but let's start with this and see how it looks :ok_hand:

**Review by andrewpbrett — APPROVED** [review]

**Comment by andrewpbrett** [comment]
Oh I didn't realize it was already configurable. Nice. So this would take effect on the next deploy?

**Review by sauloperez — APPROVED** [review]

**Comment by sauloperez** [comment]
On the next provisioning, to be precise.

**Comment by sauloperez** [comment]
I just provisioned CA

**Comment by andrewpbrett** [comment]
I did the US 👍

**Pull request merged**
