### PR TITLE
Add bugsnag key template to example secrets

### PR DESCRIPTION
**Pull request by mkllnk**
Bugsnag has been overlooked by many newcomers. Maybe that was because it was missing in the secrets template?

### CODE REVIEW

**Comment by sauloperez** [comment]
do we have a setup manual for new instances? We must have something

**Comment by sigmundpetersen** [comment]
This is what I found on Bugsnag in the wiki https://github.com/openfoodfoundation/ofn-install/wiki/Issue-reporting
Don't know if it covers it all

**Comment by luisramos0** [comment]
test ready?

**Comment by sauloperez** [comment]
Sorry, my bad. This is a no-test pr, it is for documentation purposes only so merging.

**Comment by sauloperez** [comment]
Good finding @sigmundpetersen I'll try to update it.

**Pull request merged**
