### PR TITLE
Ruby bump: ofn-install edition

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
Related to https://github.com/openfoodfoundation/openfoodnetwork/pull/4250

Provisions servers with Ruby `2.1.9`. 

The old Ruby `2.1.5` and associated gems will remain on the servers. We can tidy them up later by setting `rbenv_clean_up: true`.

### Testing:

- [x] Run `provision.yml` with these changes
- [x] Make sure Ruby `2.1.9` can be built without errors
- [x] Deploy https://github.com/openfoodfoundation/openfoodnetwork/pull/4250
- [x] Test everything is ok
- [x] Check pre-2.1.9 branches can still be deployed. 

### Ops:
- [ ] Merge this PR
- [ ] Provision all instances, including Staging servers
- [x] Merge https://github.com/openfoodfoundation/openfoodnetwork/pull/4250
- [ ] Make sure Semaphore is set to build with `2.1.9`

### CODE REVIEW

**Comment by sauloperez** [comment]
I was exactly wondering about `.ruby-version` and it clashes

```
fatal: [local_travis]: FAILED! => {"changed": false, "cmd": ["bash", "-lc", "./script/install-bundler --no-ri --no-rdoc"], "delta": "0:00:00.106471", "end": "2019-09-09 15:02:42.936124", "msg": "non-zero return code", "rc": 1, "start": "2019-09-09 15:02:42.829653", "stderr": "rbenv: version `2.1.5' is not installed (set by /home/openfoodnetwork/apps/openfoodnetwork/build/.ruby-version)", "stderr_lines": ["rbenv: version `2.1.5' is not installed (set by /home/openfoodnetwork/apps/openfoodnetwork/build/.ruby-version)"], "stdout": "", "stdout_lines": []}
```

**Comment by Matt-Yorkley** [comment]
> I was exactly wondering about `.ruby-version` and it clashes

Did you try to provision this, or are you looking at the CI build? The build will not have both versions installed because it's starting from scratch, installing `2.1.9` and then deploying `master`.

**Comment by sauloperez** [comment]
I was just looking at the CI build

**Comment by sauloperez** [comment]
So what do you suggest @Matt-Yorkley ? That we move one anyway?

**Comment by RachL** [comment]
Sorry guys but I'm opening this one once a day before remembering I cannot test it right away. Can you remove the blocked label once you've stage it?

**Comment by sauloperez** [comment]
The build is passing but failing on the linting step. Given that this is blocking many things I make the call and merge it. The lint error is due to the last commit and can easily be fixed later on. It won't affect us.

**Comment by sauloperez** [comment]
Provisioning done for all stagings. This was the result

Screenshot from 2019-09-19 09-50-45

I'll retry AU because the failure was

```
TASK [unicorn_user : Create sudoers configuration for unicorn user] *******************************************************************************************************************
Thursday 19 September 2019  09:39:06 +0200 (0:00:06.448)       0:03:22.995 ****                                                                                                       
ok: [staging.katuma.org]                                                                                                                                                              
ok: [staging.openfoodnetwork.org.uk]                                                                                                                                                  
ok: [staging.openfoodfrance.org]                                                                                                                                                      
fatal: [staging.openfoodnetwork.org.au]: FAILED! => {"msg": "Timeout (12s) waiting for privilege escalation prompt: "}    
```

**Comment by Matt-Yorkley** [comment]
We should wait for a new release with the Ruby bump before provisioning production...

**Comment by sauloperez** [comment]
the 2nd run fix au staging.

**Pull request merged**
