### PR TITLE
Added correct domain name (.org not .fr) to the config of fr_staging

### PR DESCRIPTION
**Pull request by luisramos0**
…and granted access to luis to this server.

This is part of fixing fr_staging to work normally with ofn-install.
There are still a few issues on the provisioning but the deploy is working with this change.

### CODE REVIEW

**Comment by daniellemoorhead** [comment]
#assignyourself #stopmenagging #please 🙏

**Comment by luisramos0** [comment]
This is approved, so, ready to go, right?

**Comment by daniellemoorhead** [comment]
@Matt-Yorkley @enricostano @sauloperez @mkllnk can one of you please merge this?

**Comment by Matt-Yorkley** [comment]
Do you need any other help with the deployment @luisramos0 ?

**Comment by luisramos0** [comment]
Thanks for asking Matt!
I can stage things to FR now.
There are a few things that he wanted to rebuild.
@pacodelaluna was going to have a look at it and rebuild a few things. I am not sure how far did he go with that.

**Pull request merged**
