### PR TITLE
Grant filipe access to uk staging

### PR DESCRIPTION
**Pull request by luisramos0**
This will help (a lot) @filipefurtad0 test subscriptions in the rails 4 version.

### CODE REVIEW

**Comment by lin-d-hop** [comment]
Happy for this to be merged..... but can't figure out how to actually approve :-/

**Comment by luisramos0** [comment]
Thanks!
To approve a PR you can go to the tab "Files Changed" and click "Review changes". Unless you are not in the right user group (this one is on ofn-install).

**Comment by filipefurtad0** [comment]
Thanks @lin-d-hop and @luisramos0 !

**Comment by Matt-Yorkley** [comment]
This just needs to be merged and provisioned on `uk-staging` :heavy_check_mark:

**Comment by luisramos0** [comment]
done, thanks :+1:

**Pull request merged**
