### PR TITLE
Add maintenance mode!

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
Fiiiiinally...

maintenance

It's pretty basic, but it's better than nothing. This will be really handy for downtimes, like with the v2 rollout.

Usage examples: 

```
ansible-playbooks playbooks/maintenance_mode.yml --limit uk-prod
```

```
ansible-playbooks playbooks/maintenance_mode.yml --limit uk-prod -e "disable_maintenance=true"
```

```
ansible-playbooks playbooks/maintenance_mode.yml --limit es-prod -e "maintenance_mode_message='Os dia! Donde fue el sitio!? No pasa nada, estamos manteniendo el servidor...'"
```

Tested on UK staging :heavy_check_mark:

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
The message is in English by default, but the variable `maintenance_mode_message` can be set in instances' respective config.yml files with a custom translated message.

**Comment by sauloperez** [comment]
Lol message

**Comment by mkllnk** [comment]
Interesting, the fuubar error was triggered on Travis now. I guess we should rebuild with the patch.

**Comment by sauloperez** [comment]
I added this in https://github.com/openfoodfoundation/ofn-install/wiki/Deployment-of-v2#deployment feel free to fix anything, meanwhile I merge this.

**Pull request merged**
