### PR TITLE
Lets hack letsencrypt

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
Prep for https://github.com/openfoodfoundation/openfoodnetwork/issues/5418 (and general improvement for future production server migrations).

Automates a tricky part of the process of migrating a live production server. 

This was quite a messy job before, and a bit hacky. It's critical for doing easy server migrations.

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
Tested and working :heavy_check_mark::heavy_check_mark:

**Comment by Matt-Yorkley** [comment]
> I wonder how can this be tested...

So the main thing this PR touches is the configs for the non-https entry for nginx, labelled `ofn_80`. It's used in the `provision.yml` playbook as well as the new playbook `letsencrpyt_proxy.yml`. 

On the server these configs are written to a specific file: `/etc/nginx/sites-available/ofn_80.conf`.

You can `cat` that file to see what it looks like, provision, then check the file again to see if it looks ok. It seems to add an extra blank line, but I think it's ok. From past experience I can say that if nginx is not completely happy with the file, it will complain very loudly and the CI build would already be broken.

The other test is to run the new playbook on a server and check the output looks ok. I've used this exact config before in two migrations to proxy letsencrypt checks. 

Usage: `ansible-playbook playbooks/letsencrypt.yml --limit <staging-server> -e "proxy_target=<ip-address>"`

Do you want to try a full test of the proxied letsencrypt check? It might be tricky...

**Comment by Matt-Yorkley** [comment]
Okay, I just used this live with Katuma Prod to successfully create a certificate on the new server even though the domain doesn't point to the new server's IP yet.

The **proxying voodoo** worked, and I didn't even have to sacrifice a chicken :heavy_check_mark: :chicken:

**Comment by luisramos0** [comment]
awesome! and thanks for explaining in detail!!

**Comment by Matt-Yorkley** [comment]
Temporary nginx configs for requests on port 80 on `app.katuma.org`:

Screenshot from 2020-05-15 18-26-49


Certificate on the new server (`migration.katuma.org`):

Screenshot from 2020-05-15 18-24-32

**Comment by sauloperez** [comment]
pretty neat :ok_hand: :clap:

**Pull request merged**
