### PR TITLE
Fetch secrets when deploying with Semaphore

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
This is a proposal to modify the Semaphore deployment system so that a server will automatically fetch the latest copy of it's own secrets file from the new private repo when it's deploying itself.

There's a couple of contentious bits:
- we provision the vault password into a file under `/home/ofn-admin/`, owned by `root` with 600 permissions as a one-off event when the `setup_semaphore_deployment.yml` is run against the server we're setting up. It's handled via a secure prompt, so the sysadmin provisioning it has to manually put in the password.
- in order to pull from the private repo we use a bot account, give it read access on the secrets repo, and create a Personal Access Token in the bot's account which gives access to read files in that repo and nothing else. We can then use that token programmatically to pull from the secrets repo.
- we save that token into Semaphore, using an encrypted environment variable in the Semaphore secrets UI. The secret can't be read or edited by any Semaphore users after that point (it can be deleted). We then pass it to the server that's being deployed so it can fetch the (encrypted) secrets and decrypt them with the vault-pass file.

Simple, right? :trollface:

### CODE REVIEW

**Comment by sauloperez** [comment]
Wouldn't storing the vault password in the Semaphore secrets UI make this a bit simpler? It's a 3rd but... We are not security expects either, are we?

**Comment by Matt-Yorkley** [comment]
We could definitely store it in Semaphore as well, and that might be marginally simpler. I felt it was nicer to not keep both the ability to access the secrets and the means to encrypt them in the same place and held by a third party.

**Comment by sauloperez** [comment]
That is legit too :+1:

**Comment by mkllnk** [comment]
Okay, what's the risk? If someone compromised one server, they would have access to all encrypted secrets. If every file has a different password, the attacker can only read the secrets of the host which is already compromised and you would find those secrets in the application.yml as well. I don't think we are increasing the risk by much here. :+1:

**Comment by Matt-Yorkley** [comment]
I've just realised if we finally do this: #280, then the deploy playbook actually has no dependencies on the secrets file at all, and we can deploy without it. :see_no_evil: And we can tidy up and simplify things a lot. :tada:

**Comment by mkllnk** [comment]
Awesome thought!

**Comment by sauloperez** [comment]
I really want to get rid of annoyances (I'm tired of things being stuck forever) so #280 is done. I hope no one thinks I hacked the process. It wasn't my intention.

**Pull request closed without merging**
