### PR TITLE
Ofn install cleanup

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
Cleans up temporary dual-purpose tasks that were designed to handle: 

- the transition from Rails 3 to Rails 4
- the transition from the old deployment style to the new style with symlinks

Both of these transitions are complete.

### What to test

I think the build should be enough in this case, we just need to test that deploying works. It no longer works with Rails 3.

### CODE REVIEW

**Review by sauloperez — APPROVED** [review]
:muscle: now the upgrade is really done :tada:

**Review by luisramos0 — APPROVED** [review]

**Comment by luisramos0** [comment]
The build is broken.

I think we should add the ofn PR template to ofn-install so we follow the process. I think this needs What to Test section.
and probably also this is worth Release Notes.

**Review by luisramos0 — CHANGES_REQUESTED** [review]
see comment above.

**Comment by Matt-Yorkley** [comment]
I accidentally deleted a line with an unrelated conditional that was still needed, I've put it back now and the build is green.

**Review by luisramos0 — APPROVED** [review]

**Comment by luisramos0** [comment]
I deployed with this branch to es-staging. all good :+1:

**Pull request merged**
