### PR TITLE
Don't set X-Frame-Options in nginx

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
Addressing #107.

Removing this header so it can be altered programmatically from within Rails. Needed for embedded shopfronts functionality.

### CODE REVIEW

**Comment by myriamboure** [comment]
@Matt-Yorkley any answer to @sauloperez comment? Would be great to unlock the embed shopfront issue ...

**Comment by Matt-Yorkley** [comment]
Commented-out lines have been removed.

**Comment by Matt-Yorkley** [comment]
@sauloperez @enricostano can we merge this please?

**Comment by enricostano** [comment]
@Matt-Yorkley @myriamboure have we tested this in some staging environment?

**Comment by myriamboure** [comment]
@sauloperez are you ok with the changes made by @Matt-Yorkley ? @enricostano how can we test that? Do we need to deploy https://github.com/openfoodfoundation/openfoodnetwork/pull/2026 with this branch of OFN-install on a staging and see if that fix the problem? I can ask François if that's the strategy, but please confirm as I don't know how OFN-install works.

**Comment by enricostano** [comment]
@myriamboure yep, we should provision a staging server with this banch of `ofn-install` and then deploy https://github.com/openfoodfoundation/openfoodnetwork/pull/2026 to test that the issue is solved.

**Comment by myriamboure** [comment]
It works! Seems the fix on branch OFN-install 121 did the job with https://github.com/openfoodfoundation/openfoodnetwork/pull/2026: https://docs.google.com/document/d/1EL_Cdwcx3U7LxrtLa4mwmpo6hGSiT4gzOqO-TyBfrao/edit?usp=sharing
All good, ready to go! Both of them needs to go together

**Comment by myriamboure** [comment]
I cannot add label or change the pipeline on this repo so please @enricostano or @sauloperez you can merge!

**Pull request merged**
