### PR TITLE
Toggle customer balance to French hub's managers

### PR DESCRIPTION
**Pull request by sauloperez**
Closes
https://github.com/openfoodfoundation/openfoodnetwork/issues/6708.

It's not the most elegant solution because future added/removed managers won't be taken into account but it gets the job done now.

### CODE REVIEW

**Review by RachL — APPROVED** [review]

**Review by Matt-Yorkley — APPROVED** [review]

**Comment by sauloperez** [comment]
@RachL I just provisioned and restarted Unicorn and DelayedJob we've open you the gates to customer balance :joy: . 

```rb
irb(main):002:0> user = Spree::User.find_by(email: 'rachel.arnould@openfoodfrance.org')
=> #<Spree::User id: 2831, email: "rachel.arnould@openfoodfrance.org", persistence_token: nil, perishable_token: nil, last_request_at: nil, login: "rachel.arnould@openfoodfrance.org", ship_address_id: nil, bill_address_id: nil, created_at: "2018-09-05 20:52:29", updated_at: "2021-01-05 15:28:16", authentication_token: nil, spree_api_key: "ccbba5a2b6fbd7d28d18e8db76c6d24904c28b0c60ae6efd", api_key: nil, enterprise_limit: 50, locale: "fr">
irb(main):003:0> OpenFoodNetwork::FeatureToggle.enabled?(:customer_balance, user)
=> true
```

Could you let the hub know and try it out yourself from /admin/customers?

**Comment by RachL** [comment]
I'm on it

**Comment by sauloperez** [comment]
Did they appreciate any difference? I couldn't find any logs except from a couple requests you did.

**Comment by RachL** [comment]
Have heard back from them yet, but Thursday -Friday are their delivery days, they usually work on this page on Monday - Tueasday. Stay tuned.

As for myself, I find there is a big difference - I measured it but forgot to paste here 🤦

**Comment by sauloperez** [comment]
We just did a live session searching through the logs and well, we improved by 50% since 2 weeks ago their requests took around 50s and they take now from 12 to 24s. See the request @RachL just performed: https://app.datadoghq.com/logs?cols=core_host%2Ccore_service&context_event=AQAAAXdoyZt4I0QU3wAAAABBWGRveWE0bUFBQlQ0bXJTR1NYSmpRQUE&event=&from_ts=1611766148446&index=&live=false&messageDisplay=inline&query=host%3Awww.coopcircuits.fr+service%3Anginx+filename%3Aaccess.log&saved_view&stream_sort=desc&to_event=AQAAAXdoyiQw60PQ5gAAAABBWGRveWpoa0FBQzlfOVJ3TXgwQlVRQUc&to_ts=1612370814000&viz=

These response times are still an issue for this hub. This becomes evident when they told @RachL they didn't notice any change. Of course, beyond 10s everything is crazy slow, and 24s compared to 50s is still broken.

This all we can do with this epic. At least we now know that hub 922 is a good reference or baseline to compare against. Hardly any other hub will be slower than this one.

**Pull request merged**
