### PR TITLE
Increase UK timeouts

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
Increasing timeouts for UK servers due to issue https://github.com/openfoodfoundation/openfoodnetwork/issues/2545.

### CODE REVIEW

**Comment by sigmundpetersen** [comment]
Partly duplicate of #237 ? Or is it complimentary @Matt-Yorkley ?

**Comment by Matt-Yorkley** [comment]
Ah yes, I just noticed that. @mkllnk I've added the timeout to UK staging here as well, given the servers both have the same specs and usually have similar data sets. What do you think?

**Comment by mkllnk** [comment]
In that case, it could go into the group vars, but it doesn't really matter.

**Comment by daniellemoorhead** [comment]
@luisramos0 can you have a look at this please, it would be good to get it merged ASAP so the UK team can get to the bottom of the problem.

**Comment by daniellemoorhead** [comment]
Moved this to ready to go as I assume no testing is required @Matt-Yorkley? Move into testing column if it does, or it just needs to be merged by whoever has the power.

**Comment by mkllnk** [comment]
@luisramos0 I think that the `unicorn.rb` you found is not used actually used. It's referenced in `Procfile` and that seems to be a Heroku configuration file. We don't support Heroku any more. We should remove that file as well. Are you happy to create a pull request?

**Comment by luisramos0** [comment]
yes I will. I love deleting dead code!

**Comment by daniellemoorhead** [comment]
@luisramos0 😆

**Comment by luisramos0** [comment]
PR created: [#2636 on ofn](https://github.com/openfoodfoundation/openfoodnetwork/pull/2636).

**Pull request merged**
