### PR TITLE
Add US instance

### PR DESCRIPTION
**Pull request by enricostano**
### WAT
With this PR we welcome the OFN US public instance, available at https://openfoodnetwork.net

### Related repos & PRs
Secrets and credentials: https://github.com/coopdevs/ofn-net-secrets
l10n: https://github.com/openfoodfoundation/l10n_us/pull/2

### CODE REVIEW

**Comment by enricostano** [comment]
cc/ @danypr92

**Comment by kirstenalarsen** [comment]
Yay!

**Comment by danypr92** [comment]
Hi! :wave:

**Comment by sauloperez** [comment]
nicely done @enricostano :clap:

**Comment by enricostano** [comment]
@danypr92 can we merge this PR?

**Pull request merged**
