### PR TITLE
Add Welsh language to OFN UK Prod

### PR DESCRIPTION
**Pull request by lin-d-hop**
Closes: #782 

Add the new Welsh language translation to OFN UK.

### CODE REVIEW

**Comment by lin-d-hop** [comment]
Seems this doesn't build.
@openfoodfoundation/core-devs ... any pointer on what I did wrong :(

**Comment by lin-d-hop** [comment]
@Matt-Yorkley Can you help me understand why this build fails? :pray:

**Comment by Matt-Yorkley** [comment]
Hmmm... looks like `yarn` is failing in the test suite for some reason. I'll re-run it, it might have been a temporary issue...

**Comment by lin-d-hop** [comment]
Thanks. I reran it myself a few times too. Still failing ... :-(

**Comment by Matt-Yorkley** [comment]
There's some shenanigans going on with the CI, it currently fails when building from `master` as well...

Possibly python related, I'm 99% sure this problem only appears in the test suite.

**Comment by Matt-Yorkley** [comment]
So... lets problem-solve; we can add Welsh to UK Staging as well, then we can provision and test it there before merging and provisioning UK Production :ok_hand:

**Comment by Matt-Yorkley** [comment]
LGTM https://staging.openfoodnetwork.org.uk/?locale=cy :heavy_check_mark:

**Review by Matt-Yorkley — APPROVED** [review]

**Comment by lin-d-hop** [comment]
Thanks @Matt-Yorkley and thanks for the pointers on how to check this myself.

@filipefurtad0 is this something within your world to look into? Is this just classic flakey specs?

**Comment by filipefurtad0** [comment]
Hey @lin-d-hop ,
I'm not really familiar with test-suite which we run on this repo. But I can try and have a look.

**Pull request merged**
