### PR TITLE
Increase Canada timeouts to 360

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
:snail:

### CODE REVIEW

**Comment by luisramos0** [comment]
thanks Matt!

**Comment by tschumilas** [comment]
I'm not bugging -  just trying to understand the process.  Can you tell me when this change will be effective?   I have the hub worried she won't be able to run the report tomorrow morning.  It is still timing out -  I just ran it (as hub manager).  Here is the screenshot. 
Bailey's Local Foods - OC Customer Totals report - May 12, 1pm

**Comment by luisramos0** [comment]
That shows us the change went in, it's timing out at 6mins.

The second typical workaround here is to run the report for a shorter time window @tschumilas can you try that? You can even isolate problematic days with lots of data.

**Comment by tschumilas** [comment]
Or I could run all days by groups of producers -  tried that and it worked.  But really we are saying,  even with this increased timeout,  this report won't run as one full report.

**Pull request merged**
