### PR TITLE
Disable Datadog/APM for UK, AU, CA and US

### PR DESCRIPTION
**Pull request by jibees**
Context: https://openfoodnetwork.slack.com/archives/C01T75H6G0Z/p1663927889996539

How to test: provision servers, and wait for 1 day and then check datadog

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]
So simple!

**Comment by mkllnk** [comment]
I provisioned Canada. Let's see what happens.

**Comment by mkllnk** [comment]
It looks like it worked. I should provision the other hosts, too.
Screenshot from 2022-10-03 17-14-27

**Comment by mkllnk** [comment]
- [ ] AU
- [x] CA
- [ ] UK
- [ ] US...

**Comment by mkllnk** [comment]
All done.

**Comment by RachL** [comment]
thanks @mkllnk !

**Pull request merged**
