### PR TITLE
Update ubuntu server, use same than webapp CI

### PR DESCRIPTION
**Pull request by jibees**
Ref:
https://github.com/openfoodfoundation/openfoodnetwork/blob/3a1579104fc49caf49ad894b1922984259114930/.github/workflows/build.yml#L21

Context: https://github.com/actions/runner-images/issues/6002

### CODE REVIEW

**Comment by sigmundpetersen** [comment]
I also think python 3.8.12 works for 22.04.
Maybe less work for now than bumping the minor version?

**Comment by jibees** [comment]
> I also think python 3.8.12 works for 22.04. Maybe less work for now than bumping the minor version?

I saw that error:
```
 Error: The version '3.8.2' with architecture 'x64' was not found for Ubuntu 22.04.
```

**Comment by sigmundpetersen** [comment]
Yes, and following that link in the error https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json , 3.8.12 is the first on the 3.8 branch to support 22.04.

But if 3.10.4 has a green build, that would be better of course 👍

**Comment by jibees** [comment]
> I also think python 3.8.12 works for 22.04.

Sorry I read `3.8.2` ! Ok, maybe I should do step by step, not sure.

**Comment by jibees** [comment]
I'm not sure how to progress here, maybe @Matt-Yorkley could have great ideas?

**Pull request closed without merging**
