### PR TITLE
Zero Downtime Deployments take 2

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
- Un-reverts the initial PR
- Adds this bugfix: https://github.com/openfoodfoundation/ofn-install/pull/619
- Adds additional test coverage for the transition to new deployment method

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
I've added a bunch of additional tests to the suite for this PR. We can remove them again after we've transitioned to the new deployment method.

**Comment by Matt-Yorkley** [comment]
Okay! We now have full tests that cover various combinations of deployment scenarios, including the initial "transitional" deployment where we switch between the two methods, and the tests check that everything is as it should be. :heavy_check_mark: 

Ready for re-review and some more manual tests. :rocket:

**Comment by sauloperez** [comment]
Tested and deployments or absolutely zero downtime! I found a couple of things though

### Rollbacks

I still experience the same issue with the rollbacks:

```
TASK [Gathering Facts] *************************************************************************************************************************************************************************
Wednesday 27 May 2020  08:56:47 +0200 (0:00:00.033)       0:00:00.033 ********* 
ok: [staging.katuma.org]
TASK [rollback : fetch stats of rollback symlink] **********************************************************************************************************************************************
Wednesday 27 May 2020  08:56:50 +0200 (0:00:03.112)       0:00:03.146 ********* 
ok: [staging.katuma.org]
TASK [rollback : symlink rollback source to current path] **************************************************************************************************************************************
Wednesday 27 May 2020  08:56:52 +0200 (0:00:01.416)       0:00:04.562 ********* 
changed: [staging.katuma.org]
TASK [restore database] ************************************************************************************************************************************************************************
Wednesday 27 May 2020  08:56:53 +0200 (0:00:01.320)       0:00:05.883 ********* 
TASK [db_restore : close active db connections] ************************************************************************************************************************************************
Wednesday 27 May 2020  08:56:53 +0200 (0:00:00.088)       0:00:05.971 ********* 
changed: [staging.katuma.org]
TASK [db_restore : drop database] **************************************************************************************************************************************************************
Wednesday 27 May 2020  08:56:54 +0200 (0:00:01.377)       0:00:07.349 ********* 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: DETAIL:  There is 1 other session using the database.
fatal: [staging.katuma.org]: FAILED! => {"changed": false, "msg": "Database query failed: database \"openfoodnetwork\" is being accessed by other users\nDETAIL:  There is 1 other session using the database.\n"}
RUNNING HANDLER [ensure unicorn is started] ****************************************************************************************************************************************************
Wednesday 27 May 2020  08:57:01 +0200 (0:00:06.426)       0:00:13.776 ********* 
RUNNING HANDLER [reload unicorn] ***************************************************************************************************************************************************************
Wednesday 27 May 2020  08:57:01 +0200 (0:00:00.001)       0:00:13.777 ********* 
PLAY RECAP *************************************************************************************************************************************************************************************
staging.katuma.org         : ok=4    changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
Wednesday 27 May 2020  08:57:01 +0200 (0:00:00.002)       0:00:13.780 ********* 
=============================================================================== 
db_restore : drop database -------------------------------------------------------------------------------------------------------------------------------------------------------------- 6.43s
Gathering Facts ------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 3.11s
rollback : fetch stats of rollback symlink ---------------------------------------------------------------------------------------------------------------------------------------------- 1.42s
db_restore : close active db connections ------------------------------------------------------------------------------------------------------------------------------------------------ 1.38s
rollback : symlink rollback source to current path -------------------------------------------------------------------------------------------------------------------------------------- 1.32s
restore database ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 0.09s
reload unicorn -------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.00s
ensure unicorn is started --------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.00s
```

On a second attempt it succeeds.

performing the same test (deploying and then rolling back) from master succeeds. I fail to see what in this branch could affect the killing of DB connections. Perhaps the way we now reload the worker processes? Given rollbacks involves downtime already, we could simply stop Unicorn and DJ before restoring the DB.

### Rails version check

It's very odd that the following task

```
TASK [deploy : check rails version in Gemfile] *************************************************************************************************************************************************
ok: [staging.katuma.org]
Wednesday 27 May 2020  09:03:35 +0200 (0:00:01.133)       0:01:31.962 ********* 
```

it's abnormally slow in Katuma staging, at least, making the deployment even slower than it already is.

@Matt-Yorkley would you mind creating two separate issues and perhaps taking a quick look. I'm just hoping we could amend one or the two quickly enough.

**Comment by Matt-Yorkley** [comment]
@sauloperez New issues added here: #623, #624.

**Comment by sauloperez** [comment]
Moving on then.

**Pull request merged**
