### PR TITLE
Increase unicorn_workers to 4 for UK production

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
Delivery of additional unicorns to the UK, as ordered in #356.

UNICORNS

### CODE REVIEW

**Comment by sauloperez** [comment]
Keep us posted, brits :gb: !

**Comment by lin-d-hop** [comment]
I love magical unicorns!

**Comment by mkllnk** [comment]
@Matt-Yorkley Did you know that you are still running with three unicorns?

```
openfoodnetwork@production18:~$ ps -fC bundle
UID        PID  PPID  C STIME TTY          TIME CMD
openfoo+ 31896     1  0 Apr15 ?        00:00:00 unicorn master -D -c /home/openfoodnetwork/apps/openfoodnetwork/shared/config/unicorn.rb -E production
openfoo+ 31899 31896  2 Apr15 ?        02:22:54 unicorn worker[0] -D -c /home/openfoodnetwork/apps/openfoodnetwork/shared/config/unicorn.rb -E production
openfoo+ 31902 31896  2 Apr15 ?        02:20:16 unicorn worker[1] -D -c /home/openfoodnetwork/apps/openfoodnetwork/shared/config/unicorn.rb -E production
openfoo+ 31904 31896  3 Apr15 ?        02:27:21 unicorn worker[2] -D -c /home/openfoodnetwork/apps/openfoodnetwork/shared/config/unicorn.rb -E production
```

The config is right but unicorn hasn't been reloaded. I leave that one up to you.

**Comment by Matt-Yorkley** [comment]
Thanks @mkllnk! I've reloaded UK production, and the new workers are up. I also updated the handlers  here: #407

**Pull request merged**
