### PR TITLE
auto confirm admin user after seeding database

### PR DESCRIPTION
**Pull request by elf-pavlik**
Fixes: #139

---
This change is [Reviewable](https://reviewable.io/reviews/openfoodfoundation/ofn-install/146)

### CODE REVIEW

**Comment by elf-pavlik** [comment]
I don't know what this has to do with `dev:load_sample_data`?

In staging and production environment it also comes helpful to have the admin confirmed and not have to use email confirmation steps.

**Comment by sauloperez** [comment]
We do all the sample data setup from that rake task, and we already autoconfirm the spree user there. See https://github.com/openfoodfoundation/openfoodnetwork/blob/master/lib/tasks/dev.rake#L206

**Comment by elf-pavlik** [comment]
Do you have clear suggestion of how to extract https://github.com/openfoodfoundation/openfoodnetwork/blob/master/lib/tasks/dev.rake#L206 into something that both `dev.rake` and playbook can reuse?

Last years I work mostly with javascript, gulp etc. and don't have a that good of a grip on ruby and rake.

Would extracting confirmation into a separate task, which this playbook would run (instead of `rails runner` used in this PR)  and then also using it in `dev.rake` as suggested here: https://coderwall.com/p/no2w6g/invoke-a-rake-task-from-another-task make sense for you?

**Comment by mkllnk** [comment]
I also think that this is not the right approach. Sample data is not right either, because that's not for production servers. We should probably look into the generation of the user in Spree (rake db:setup) and do it there.

**Comment by elf-pavlik** [comment]
Maybe someone could make PR with an alternative approach? This one just automates what otherwise I have to do manually to log in to admin interface. Otherwise this one could land as imperfect but working and new Issue could track ideas for better approach until someone comes up with PR.
I really find it important that one can run this playbook, it runs successful and then open a browser and log in right away. Once there it can take a lot of improvements while always making sure to keep smooth deployment experience.

**Comment by mkllnk** [comment]
Yes, I think you are right. It's not the best approach, but it is a solution and we should use it until we have a better one.

**Comment by enricostano** [comment]
We're making an effort to decouple server provisioning and deploy from application logic, let's try to move all together in that direction if you agree.

I think that this should be in the `db:seed` data rake task, that is called every time you call `db:setup` rake task.

May we close this in favour of https://github.com/openfoodfoundation/openfoodnetwork/issues/2182 ?

**Comment by sauloperez** [comment]
And executed on deploy:

https://github.com/openfoodfoundation/ofn-install/blob/92ca2af690412cd64a4f8d46f36ac8d42714ec12/roles/deploy/tasks/main.yml#L189-L200

**Comment by enricostano** [comment]
@sauloperez 

> And executed on deploy

I think we should be able to remove it from there, could you please open an issue to investigate that?

**Comment by elf-pavlik** [comment]
> May we close this in favour of openfoodfoundation/openfoodnetwork#2182

**Pull request closed without merging**
