### PR TITLE
Pull translations while deploying

### PR DESCRIPTION
**Pull request by pacodelaluna**
We have always to update translations manually while deploying on french side. I guess the other way to do this is to merge directly translations to the master branch, but should we really add a new commit each time a translation changed?

By the way, it is my first task with Ansible, so I am lacking best practices I guess, tell if if any issue at this side.

### CODE REVIEW

**Comment by sauloperez** [comment]
That's an interesting approach. I wonder what needs to happen with the git branch then? I guess the translation will be available to the app but they will have to be brought to master as well. So should we keep opening a Transifex PR?

**Comment by pacodelaluna** [comment]
Well, it was just an idea. I will push a new PR with french translations to have an updated master branch.

**Comment by sauloperez** [comment]
As long as we keep master up to date this seems good to me.

**Comment by sauloperez** [comment]
The latest changes in our Transifex integration should solve this kind of issues.

**Pull request closed without merging**
