### PR TITLE
Grant access for Mikel to Katuma

### PR DESCRIPTION
**Pull request by dacook**
Awaiting confirmation before merging:
- [x] * Mikel is authorised to access the Katuma server?
- [x] * Mikel's public key is current?

Also should these keys be removed from Katuma?
* `dani <danypr92@gmail.com>`
* `enricostn`

### CODE REVIEW

**Comment by dacook** [comment]
@NickWeir63 , are you able to confirm that Mikel may have access to the Katuma server?

@mcmpp, can you confirm if this is your current public key? It is currently granted access to app.openfoodswitzerland.ch
https://github.com/openfoodfoundation/ofn-install/blob/master/files/keys/mikel.pub
Also, shall we set the `developer_email` for Katuma as per [ch.yml](https://github.com/openfoodfoundation/ofn-install/blob/master/inventory/group_vars/ch.yml#L16-L17)? 

And can anybody confirm, should these keys be removed from Katuma?
* `dani <danypr92@gmail.com>`
* `enricostn`

**Comment by mcmpp** [comment]
Hi @dacook , 

yes, I can confirm that this is my current key, so the change should be enough to grant me access. I would not change the developer email. 
I cannot confirm who else should have access to this server. 

Sorry that I can only answer to the first question. @NickWeir63, can you answer to any of the remaining questions?

**Comment by dacook** [comment]
Ready to go. Nick has asked Eugeni about the other users, but we can address that in a future PR if needed.

**Review by rioug — APPROVED** [review]

**Comment by dacook** [comment]
Hi @mcmpp , this has now been provisioned:

```
ansible-playbook playbooks/provision.yml --limit es_prod --tags ssh_keys
...
TASK [ssh_keys : add ssh keys users_sysadmin] ***************************************************************************
ok: [app.katuma.org] => (item=maikel)
ok: [app.katuma.org] => (item=matt)
ok: [app.katuma.org] => (item=filipe)
ok: [app.katuma.org] => (item=david)
ok: [app.katuma.org] => (item=gaetan)
ok: [app.katuma.org] => (item=dani)
ok: [app.katuma.org] => (item=enricostn)
changed: [app.katuma.org] => (item=mikel)
```

**Comment by dacook** [comment]
I didn't actually check the keys on the server before, and it's possible that other keys have been added that aren't recorded in ofn-install, so I am checking now. 
These are the names given for each key. At first glance this looks similar to what's expected, but as I don't have any information about removing keys I won't inspect further.
```
ofn-admin@katuma-production:~$ grep -o '\s\S*$' .ssh/authorized_keys
 maikel@max

 ofn
 danypr92@gmail.com
 apb@iMac.local
 filipefurtado@gmail.com
 Davids-MBP
 gaetan@openfoodnetwork.org.au
 pelayo@llar
 jordi@jordi-coopdevs
 kon
 mkordo@gmail.com
```

**Pull request merged**
