### PR TITLE
Update konrad.pub

### PR DESCRIPTION
**Pull request by jibees**
The title says it all.

### CODE REVIEW

**Review by filipefurtad0 — APPROVED** [review]

**Comment by jibees** [comment]
I've merged, and provisioned `uk-staging`
Please @drummer83, let me know.

**Comment by drummer83** [comment]
I will try tonight!
Thanks JB!

**Comment by drummer83** [comment]
Hi @jibees,
here is what I get... :cry: 
```
konrad@Lenovo-IdeaPad-Y500:~$ ssh openfoodnetwork@staging.openfoodnetwork.org.uk
openfoodnetwork@staging.openfoodnetwork.org.uk: Permission denied (publickey).
```

**Comment by drummer83** [comment]
Maybe stupid question... Do I have to do anything with my private key? I only have it lying around in the .ssh folder. Is that ok?

**Comment by jibees** [comment]
> Do I have to do anything with my private key? I only have it lying around in the .ssh folder. Is that ok?

No that's ok. When creating a key, you will have a public key: `id_rsa.pub` and a private one: `id_rsa` in the `~/.ssh` folder.

**Pull request merged**
